### ISSUE TITLE
ノートに作成日と更新日を任意の位置に配置する方法

### ISSUE THREAD

**Issue by blacktanktop** [tadashi-aikawa/obsidian-questions#13]
いつもお世話になっております。
Minervaでは、記事の右上に作成日と更新日のタグが用意されていると思います。

おそらくフロントマターから値を取得されていて、更に任意の位置に配置し表示されるように工夫をされていると思っております。
Minervaの過去記事を色々と拝見したのですが、こちらのやり方を教えていただけないでしょうか？

私の環境では、Minervaに書いてあった通りTempaterでフロントマターにcreatedとupdatedを挿入する形を取っております。

**Comment by tadashi-aikawa** [comment]
@blacktanktop 
[『任意のプロパティを任意のデザインで表示する場合』](https://minerva.mamansoft.net/%F0%9F%93%97Obsidian%E9%80%86%E5%BC%95%E3%81%8D%E3%83%AC%E3%82%B7%E3%83%94/%F0%9F%93%97Obsidian+Publish%E3%81%AE%E3%82%B5%E3%82%A4%E3%83%88%E3%81%AB%E3%83%97%E3%83%AD%E3%83%91%E3%83%86%E3%82%A3(%E3%83%A1%E3%82%BF%E3%83%87%E3%83%BC%E3%82%BF)%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%97%E3%81%9F%E3%81%84#%E4%BB%BB%E6%84%8F%E3%81%AE%E3%83%97%E3%83%AD%E3%83%91%E3%83%86%E3%82%A3%E3%82%92%E4%BB%BB%E6%84%8F%E3%81%AE%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E3%81%A7%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B%E5%A0%B4%E5%90%88) を参考にしてみてください。

> Tempaterでフロントマターにcreatedとupdatedを挿入する形を取っております

とありますので、Minervaと同じ表示で問題なければそのまま動くと思います。

> **Note**
> もちろんObsidian PublishでJavaScriptを動作させる方法... 具体的には『独自ドメインの設定』が必要になります

参考までに挿入したHTMLの `.tag` クラスは以下のCSSを適応しています。

```css
/* 日付タグ */
.markdown-preview-view .tag[href*="#20"]::before {
  display: inline-block;
  filter: invert(0.4) hue-rotate(180deg);
  width: 14px;
  content: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgNTEyIDUxMiI+PHBhdGggZD0iTTQ4MCAxMjhhNjQgNjQgMCAwIDAtNjQtNjRoLTE2VjQ4LjQ1YzAtOC42MS02LjYyLTE2LTE1LjIzLTE2LjQzQTE2IDE2IDAgMCAwIDM2OCA0OHYxNkgxNDRWNDguNDVjMC04LjYxLTYuNjItMTYtMTUuMjMtMTYuNDNBMTYgMTYgMCAwIDAgMTEyIDQ4djE2SDk2YTY0IDY0IDAgMCAwLTY0IDY0djEyYTQgNCAwIDAgMCA0IDRoNDQwYTQgNCAwIDAgMCA0LTR6IiBmaWxsPSJjdXJyZW50Q29sb3IiPjwvcGF0aD48cGF0aCBkPSJNMzIgNDE2YTY0IDY0IDAgMCAwIDY0IDY0aDMyMGE2NCA2NCAwIDAgMCA2NC02NFYxNzlhMyAzIDAgMCAwLTMtM0gzNWEzIDMgMCAwIDAtMyAzem0zNDQtMjA4YTI0IDI0IDAgMSAxLTI0IDI0YTI0IDI0IDAgMCAxIDI0LTI0em0wIDgwYTI0IDI0IDAgMSAxLTI0IDI0YTI0IDI0IDAgMCAxIDI0LTI0em0tODAtODBhMjQgMjQgMCAxIDEtMjQgMjRhMjQgMjQgMCAwIDEgMjQtMjR6bTAgODBhMjQgMjQgMCAxIDEtMjQgMjRhMjQgMjQgMCAwIDEgMjQtMjR6bTAgODBhMjQgMjQgMCAxIDEtMjQgMjRhMjQgMjQgMCAwIDEgMjQtMjR6bS04MC04MGEyNCAyNCAwIDEgMS0yNCAyNGEyNCAyNCAwIDAgMSAyNC0yNHptMCA4MGEyNCAyNCAwIDEgMS0yNCAyNGEyNCAyNCAwIDAgMSAyNC0yNHptLTgwLTgwYTI0IDI0IDAgMSAxLTI0IDI0YTI0IDI0IDAgMCAxIDI0LTI0em0wIDgwYTI0IDI0IDAgMSAxLTI0IDI0YTI0IDI0IDAgMCAxIDI0LTI0eiIgZmlsbD0iY3VycmVudENvbG9yIj48L3BhdGg+PC9zdmc+");
  margin-right: 5px;
  position: absolute;
  top: 0; /* publishだと0 */
  left: 7px;
}
.markdown-preview-view .tag[href*="#20"] {
  position: relative;
  vertical-align: middle;
  padding-left: 23px;
}
```

**Comment by blacktanktop** [comment]
ありがとうございます。こちらの記事を見落としておりました。

やってみて気づいたのですが、2番の手法だとHTMLでの操作でPublishされた状態だと表示されるものであって、ローカルの状態ではこのような描画はできないですね。（私はpublishせずにローカルで使っております。）

1番の手法でも、何日なのかということはわかるのですが、実は本当にやりたかったことはクリックして日付のデイリーノートに飛びたいということだったので、質問のタイトルが悪くて申し訳なかったですが、**ローカルの状態**でもこのような形で上部に作成日と更新日の日付タグをフロントマターから取得し、ページの上部に配置し（できれば書き出しの左上ではなくじゃまにならない右上に）クリックしてその日のページに戻れたらいいなと思っての質問でした。
ローカルで見た目は多少異なるとしてもPublishと類似した形がとれないかなという意図でした。

**Comment by tadashi-aikawa** [comment]
@blacktanktop 

> 実は本当にやりたかったことはクリックして日付のデイリーノートに飛びたい

Templaterでスクリプトを書くか、プラグインを作らないと実現は厳しそうな気がします。『Reading View』と『Editing View』どちらのケースでしょうか?

**Comment by blacktanktop** [comment]
Templaterでどうにか突っ込むというのが良いのかなとなんとなく思っておりました。
『Editing View』のほうが使っていることが多いので、『Editing View』を想定したいです

**Comment by tadashi-aikawa** [comment]
興味深い内容ですので、空き時間に私の方でもチャレンジしてみますね。

**Comment by blacktanktop** [comment]
ありがとうございます。助かります。

**Comment by tadashi-aikawa** [comment]
@blacktanktop 
多分できました。 (プラグインを作った方が早かったかもしれません... 😅 )

## 手順1

Templater実行用のスクリプトとして以下を作成してください。ファイル名は自由ですが、私は `📅Show floating date properties automatically` としたのでそのつもりで説明を続けます。

```js
<%*
const activeMarkdownView = app.workspace.getActiveFileView()
const className = "additional-date-properties"

/**
/  日付文字列からデイリーノートのパスを生成する
/  @param dateStr (ex: 2023-10-09)
*/
function toDailyNotePath(dateStr) {
  // TODO: Vaultのデイリーノートのパスになるよう設定が必要
  return `_Privates/Daily Notes/${dateStr}.md`
}

/**
/  内部リンクのDOMを作成する
/  @param fileBasename (ex: 2023-10-09)
/  @param title (ex: 作成: 2023-10-09)
*/
function createInternalLinkElement(fileBasename, title) {
  const el = createDiv({
    text: title,
    cls: "additional-date-properties__date-button"
  });

  // クリックしたときにファイルへ移動する
  // Ctrl押しながらで新しいタブで開く(macOSのcmdならev.ctrlKeyを変更する)
  el.addEventListener("click", (ev) => {
    app.workspace.openLinkText("", toDailyNotePath(fileBasename), ev.ctrlKey)
  });
  
  return el;
}

/**
/  追加UIを追加する
*/
function addAdditionalUI(file) {
  // 現在のファイルからフロントマターを取得
  const frontmatter = app.metadataCache.getFileCache(file).frontmatter
  // フロントマターがなければ中断
  if (!frontmatter) {
    return
  }

  // フロントマターから作成日と更新日を取得
  const { created, updated } = frontmatter;
  // 作成日がなければ中断 (作成日がなければ更新日もない前提)
  if (!created) {
    return
  }

  // 作成日と更新日のDOMを作成する
  const createdEl = createInternalLinkElement(created, `作成日: ${created}`)
  const updatedEl = updated ? createInternalLinkElement(updated, `更新日: ${updated}`) : undefined

  // 差し込み用DOMを構築する
  const additionalEl = createDiv({ cls: className});
  additionalEl.appendChild(createdEl);
  additionalEl.appendChild(updatedEl);

  // DOMをヘッダの手前に挿入する
  activeMarkdownView.containerEl
    .find(".view-header")
    .insertAdjacentElement("beforebegin", additionalEl);
}

/**
/  追加UIを削除する (存在しない場合は何もしない)
*/
function removeAdditionalUI(file) {
  activeMarkdownView.containerEl.find(`.${className}`)?.remove();
}

// ファイル起動時に自動で実行する処理
app.workspace.on("file-open", (file) => {
  removeAdditionalUI(file);
  addAdditionalUI(file);
});

// 初回だけはイベントが発生しないので明示的に実行
addAdditionalUI(app.workspace.getActiveFile());
%>
```

## 手順2

上記スクリプトのTODO部分

```js
function toDailyNotePath(dateStr) {
  // TODO: Vaultのデイリーノートのパスになるよう設定が必要
  return `_Privates/Daily Notes/${dateStr}.md`
}
```

パスがご自身のデイリーノート用パスになるよう調整してください。

## 手順3

CSSに以下のような設定を追加してください。

```css
.additional-date-properties {
    height: 30px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 75%;
    gap: 8px;
}
.additional-date-properties__date-button {
    cursor: pointer;  
}
```

## 手順4

Templaterの設定から `Startup Templates` に先ほどのスクリプトを設定してください。

![image](https://github.com/tadashi-aikawa/obsidian-questions/assets/9500018/723626a7-25c1-498d-8be1-34a5d0928ad5)

手順は以上です。

## 確認方法

Obsidianを再起動してください。起動直後、以下のようなViewが表示されれば成功です。

![image](https://github.com/tadashi-aikawa/obsidian-questions/assets/9500018/d5b59089-da66-4d84-a1e4-6c6d4520ede7)

日付をクリックするとデイリーノートに飛びます。 `Ctrl` 押しながらクリックで新しいタブに開きます。

----

ご不明な点ありましたら返信いただければと思います。

安定して動作するようなら Minerva のレシピにも追加しようと思っておりますので、後日使用感を報告いただけるとありがたいです 🙏
